### PR TITLE
update dependencies to use peerDependencies

### PR DESCRIPTION
**Pull request by ohadlevy**
It seems that in some cases, using this package end up pulling a wrong version of DataTables, this change prevent that.

see https://github.com/yarnpkg/yarn/issues/4176 for more info / backgroud.

Thanks!

### CODE REVIEW

**Comment by DataTables** [comment]
Hi - Thanks for the PR!

I'm not certain that a peerDependency is quite right here, based on my reading of the [package.json description](https://docs.npmjs.com/files/package.json):

> In some cases, you want to express the compatibility of your package with a host tool or library, while not necessarily doing a require of this host

However, The Bootstrap integration for DataTables _does_ do a require [on `datatables.net`](https://github.com/DataTables/Dist-DataTables-Bootstrap/blob/a1c5b3f62c54cda3639845bdf1427448ed68cd78/js/dataTables.bootstrap.js#L31) since it modifies the default values of that package. In the same way, DataTables can't use jQuery as a peerDependency since it actually does use the jQuery methods.

The other thing in the documentation is that it states as of npm 3, peerDepedencies will not be automatically installed. So if you just install `datatables.net-bs` and require it, you'll get an error since `datatables.net` wouldn't have been installed.

Very good chance I'm missing something here, apologies if so, but this doesn't look like quite the right thing to use here?

**Comment by ohadlevy** [comment]
@DataTables thanks for your review..

I was suggesting it based on https://github.com/yarnpkg/yarn/issues/3951#issuecomment-316424639.

reading https://yarnpkg.com/lang/en/docs/dependency-types/#toc-peerdependencies it sounds like this is exactly what we want to achieve in this case, direct mapping between the two packages?

**Comment by DataTables** [comment]
Yes, that documentation makes it sounds like exactly what we would want. But the npm documentation doesn't.

I wonder if in this case, the correct thing to do would actually be to have this package with a dependency (not a peer dependency) on a specific version of DataTables. Currently I've used `"datatables.net": ">=1.10.9"` - perhaps it should be `"datatables.net": "1.10.15"` to match the current release. Your own package would use `"datatables.net":"^1.10.9"` or similar.

**Comment by ohadlevy** [comment]
@DataTables thanks - I'm fine with either way that solves the problem :-)

**Comment by ohadlevy** [comment]
@DataTables ping on this? this is 100% broken when using yarn..

**Comment by DataTables** [comment]
I'm working on everything that needs to be done around this. In order to fix this I need to release a new version of DataTables, and there are other things I want to get in for it as well along with other software releases which should happen alongside it. Perhaps today, perhaps tomorrow depending on how well things go!

**Comment by mmoll** [comment]
@DataTables what's the status here?

**Comment by DataTables** [comment]
Still working on other fixes that I want to get into the release. Working as fast as possible on it!

**Comment by DataTables** [comment]
Should be good to go now. Appears to be working in my tests.

**Comment by ohadlevy** [comment]
thanks @DataTables for the release, closing

**Comment by ohadlevy** [comment]
I've just tested this again, it seems the issue still persists even with latest version.

**Comment by ohadlevy** [comment]
any update on this? thanks.

**Comment by DataTables** [comment]
Sorry - I had missed the reopening.

It [should](https://github.com/DataTables/Dist-DataTables-Bootstrap/blob/64c5a8ee533123d2943de9bca90c688de9e62498/package.json#L28) always be pulling in 1.10.16 now.

Are you just doing `npm install datatables.net-bs`?

**Pull request closed without merging**
